name: java-status-check

on:
  push:
    paths:
      - 'Java/**'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: JUnit
        run: |
          cd Java
          source aliases.sh
          ant
          junit