name: Status Check

on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Run PHP unit tests
        run: |
          cd PHP
          source aliases.sh
          composer install
          phpunit
